# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 14:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='advinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advimg', models.ImageField(upload_to='image/adv')),
                ('Advtitle', models.CharField(max_length=255)),
                ('Advcommid', models.IntegerField()),
                ('AdvCreatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='commditydetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodUnit', models.CharField(max_length=50, null=True)),
                ('CodSpec', models.CharField(max_length=50, null=True)),
                ('CodunPrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='commodityclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CclassName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='commodityendinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CeiViewNum', models.BigIntegerField(default=0)),
                ('CeiBuyNUm', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='commodityinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CommName', models.CharField(max_length=100, unique=True)),
                ('CommInfo', models.URLField()),
                ('CreateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='custcollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CollectDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='custcommprice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CpunPrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='custsalebind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Binddate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='newsclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nclassname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='newsinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Newsimg', models.ImageField(upload_to='image/new')),
                ('Newsurl', models.FileField(upload_to='News/')),
                ('Newstitle', models.CharField(max_length=255)),
                ('NewsCreatetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='shoppingcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScNum', models.IntegerField()),
                ('ScunPrice', models.FloatField()),
                ('ScSum', models.FloatField()),
                ('ScAddDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='shoppingendflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SefClass', models.CharField(max_length=50)),
                ('SefName', models.CharField(max_length=100)),
                ('SefUnit', models.CharField(max_length=50)),
                ('SefSpec', models.CharField(max_length=50)),
                ('SefunPrice', models.FloatField()),
                ('SefNum', models.IntegerField()),
                ('SefPrice', models.FloatField()),
                ('SefCreate', models.DateTimeField()),
                ('SefFinishtime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='shoppingflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sfstatus', models.IntegerField()),
                ('SfCreatetime', models.DateTimeField(auto_now_add=True)),
                ('SfModtime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='userbind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Userphone', models.CharField(max_length=30, null=True)),
                ('Userwx', models.CharField(max_length=50, null=True)),
                ('UserAddress', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='userrole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rolename', models.CharField(max_length=50)),
                ('ReleaseAdv', models.BooleanField()),
                ('ReleaseNew', models.BooleanField()),
                ('ReleaseInfo', models.BooleanField()),
                ('AddCommodity', models.BooleanField()),
                ('ModCommodity', models.BooleanField()),
                ('AddOrder', models.BooleanField()),
                ('ModOrder', models.BooleanField()),
                ('ModOrderPrice', models.BooleanField()),
                ('AppOrder', models.BooleanField()),
                ('AckOrder', models.BooleanField()),
                ('PaidOrder', models.BooleanField()),
                ('ShipOrder', models.BooleanField()),
                ('RecOrder', models.BooleanField()),
                ('TranInfo', models.BooleanField()),
                ('SalePer', models.BooleanField()),
                ('ProSummary', models.BooleanField()),
                ('ModRule', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='userrule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReleaseAdv', models.BooleanField()),
                ('ReleaseNew', models.BooleanField()),
                ('ReleaseInfo', models.BooleanField()),
                ('AddCommodity', models.BooleanField()),
                ('ModCommodity', models.BooleanField()),
                ('AddOrder', models.BooleanField()),
                ('ModOrder', models.BooleanField()),
                ('ModOrderPrice', models.BooleanField()),
                ('AppOrder', models.BooleanField()),
                ('AckOrder', models.BooleanField()),
                ('PaidOrder', models.BooleanField()),
                ('ShipOrder', models.BooleanField()),
                ('RecOrder', models.BooleanField()),
                ('TranInfo', models.BooleanField()),
                ('SalePer', models.BooleanField()),
                ('ProSummary', models.BooleanField()),
                ('ModRule', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='webdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datatime', models.DateTimeField(auto_now_add=True)),
                ('DataClassid', models.IntegerField()),
                ('DataText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='webuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Userstatus', models.IntegerField(default=0)),
                ('Createtime', models.DateTimeField(auto_now=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='webdata',
            index=models.Index(fields=['Datatime', 'DataClassid'], name='HdWxShop_we_Datatim_aa218b_idx'),
        ),
        migrations.AddField(
            model_name='userrule',
            name='Roleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HdWxShop.userrole'),
        ),
        migrations.AddField(
            model_name='userrule',
            name='Userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HdWxShop.webuser'),
        ),
        migrations.AddField(
            model_name='userbind',
            name='userid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HdWxShop.webuser'),
        ),
        migrations.AddField(
            model_name='shoppingflow',
            name='Scid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HdWxShop.shoppingcart'),
        ),
        migrations.AddIndex(
            model_name='shoppingendflow',
            index=models.Index(fields=['SefClass', 'SefName'], name='HdWxShop_sh_SefClas_661720_idx'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='ScCollectid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HdWxShop.custcollect'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='ScUserid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HdWxShop.webuser'),
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='Newsclassid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HdWxShop.newsclass'),
        ),
        migrations.AddField(
            model_name='custsalebind',
            name='Customerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customerid_Webuser', to='HdWxShop.webuser'),
        ),
        migrations.AddField(
            model_name='custsalebind',
            name='Saleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Saleid_Webuser', to='HdWxShop.webuser'),
        ),
        migrations.AddField(
            model_name='custcommprice',
            name='Cpcommid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HdWxShop.commditydetail'),
        ),
        migrations.AddField(
            model_name='custcommprice',
            name='Cpuserid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HdWxShop.webuser'),
        ),
        migrations.AddField(
            model_name='custcollect',
            name='CcCommid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HdWxShop.commditydetail'),
        ),
        migrations.AddField(
            model_name='custcollect',
            name='CcUserid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HdWxShop.webuser'),
        ),
        migrations.AddField(
            model_name='commodityinfo',
            name='Commclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HdWxShop.commodityclass'),
        ),
        migrations.AddField(
            model_name='commodityendinfo',
            name='Commid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HdWxShop.commodityinfo'),
        ),
        migrations.AddField(
            model_name='commditydetail',
            name='Commid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HdWxShop.commodityinfo'),
        ),
        migrations.AddIndex(
            model_name='webuser',
            index=models.Index(fields=['userid'], name='HdWxShop_we_userid__8f296a_idx'),
        ),
        migrations.AddIndex(
            model_name='userrule',
            index=models.Index(fields=['Userid', 'Roleid'], name='HdWxShop_us_Userid__8f5f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='userbind',
            index=models.Index(fields=['userid'], name='HdWxShop_us_userid__7af669_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingflow',
            index=models.Index(fields=['Scid'], name='HdWxShop_sh_Scid_id_8683db_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingcart',
            index=models.Index(fields=['ScUserid', 'ScCollectid'], name='HdWxShop_sh_ScUseri_9d5861_idx'),
        ),
        migrations.AddIndex(
            model_name='newsinfo',
            index=models.Index(fields=['Newsclassid'], name='HdWxShop_ne_Newscla_73a84a_idx'),
        ),
        migrations.AddIndex(
            model_name='custsalebind',
            index=models.Index(fields=['Customerid'], name='HdWxShop_cu_Custome_88a55c_idx'),
        ),
        migrations.AddIndex(
            model_name='custcommprice',
            index=models.Index(fields=['Cpuserid', 'Cpcommid'], name='HdWxShop_cu_Cpuseri_9158da_idx'),
        ),
        migrations.AddIndex(
            model_name='custcollect',
            index=models.Index(fields=['CcUserid', 'CcCommid'], name='HdWxShop_cu_CcUseri_855caf_idx'),
        ),
        migrations.AddIndex(
            model_name='commodityinfo',
            index=models.Index(fields=['Commclass'], name='HdWxShop_co_Commcla_22905e_idx'),
        ),
        migrations.AddIndex(
            model_name='commodityendinfo',
            index=models.Index(fields=['Commid'], name='HdWxShop_co_Commid__a0aae3_idx'),
        ),
        migrations.AddIndex(
            model_name='commditydetail',
            index=models.Index(fields=['Commid'], name='HdWxShop_co_Commid__a6b48c_idx'),
        ),
    ]
