# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HdWxShop', '0001_initial'),
    ]

    operations = [
    ]
