# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 07:53
from __future__ import unicode_literals
import HdWxShop.models
from django.db import migrations
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('HdWxShop', '0002_remove_shoppingendflow_sefcreatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingendflow',
            name='sefcreatetime',
            field=models.DateTimeField(verbose_name='创建时间')
        ),
    ]
