# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 08:46
from __future__ import unicode_literals

import HdWxShop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HdWxShop', '0002_auto_20180115_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advinfo',
            options={'verbose_name': '广告信息', 'verbose_name_plural': '广告信息'},
        ),
        migrations.AlterModelOptions(
            name='newsclass',
            options={'verbose_name': '新闻种类', 'verbose_name_plural': '新闻种类'},
        ),
        migrations.AlterModelOptions(
            name='newsinfo',
            options={'verbose_name': '新闻信息', 'verbose_name_plural': '新闻信息'},
        ),
        migrations.RemoveField(
            model_name='newsinfo',
            name='Newsimg',
        ),
        migrations.RemoveField(
            model_name='newsinfo',
            name='Newsurl',
        ),
        migrations.AddField(
            model_name='newsinfo',
            name='Newsbody',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shoppingendflow',
            name='SefCarryPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shoppingflow',
            name='SfCarryPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='shoppingflow',
            name='SfisCarryPrice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advinfo',
            name='Advimg',
            field=models.ImageField(upload_to=HdWxShop.models.upload_advimg),
        ),
        migrations.AlterField(
            model_name='commditydetail',
            name='CodSpec',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='commditydetail',
            name='CodUnit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='shoppingflow',
            name='Sfstatus',
            field=models.IntegerField(choices=[(1, '有意向'), (2, '生成已订单'), (3, '价格待审核'), (4, '客户待确认'), (5, '待付款'), (6, '待出货'), (7, '待收货')], verbose_name='订单状态'),
        ),
    ]
