# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HdWxShop', '0003_auto_20180130_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingendflow',
            name='SefRemark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shoppingflow',
            name='SfRemark',
            field=models.TextField(blank=True),
        ),
    ]
