# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HdWxShop', '0003_remove_shoppingendflow_sefcreatetime'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shoppingendflow',
            name='HdWxShop_sh_Sefflow_010d53_idx',
        ),
        migrations.AlterField(
            model_name='shoppingendflow',
            name='Sefflowid',
            field=models.IntegerField(verbose_name='订单号'),
        ),
        migrations.AddIndex(
            model_name='shoppingendflow',
            index=models.Index(fields=['Sefflowid', 'sefuserid'], name='HdWxShop_sh_Sefflow_3fa797_idx'),
        ),
    ]
