# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 14:00
from __future__ import unicode_literals

import HdWxShop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HdWxShop', '0004_auto_20180220_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='commditydetail',
            name='CodUnmun',
            field=models.IntegerField(blank=True, null=True, verbose_name='每件数量'),
        ),
        migrations.AddField(
            model_name='commditydetail',
            name='Codinventory',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='库存'),
        ),
        migrations.AddField(
            model_name='commodityinfo',
            name='Commimg',
            field=models.ImageField(blank=True, upload_to=HdWxShop.models.upload_commodityimg),
        ),
        migrations.AddField(
            model_name='shoppingendflow',
            name='SefUnmun',
            field=models.IntegerField(blank=True, null=True, verbose_name='每件数量'),
        ),
        migrations.AlterField(
            model_name='commodityinfo',
            name='CommInfo',
            field=models.ImageField(blank=True, upload_to=HdWxShop.models.upload_commodityinfo),
        ),
    ]
