# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-17 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HdWxShop', '0005_auto_20180417_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='setcustprice',
            field=models.BooleanField(default=False, verbose_name='设置客户价格'),
        ),
        migrations.AddField(
            model_name='userrule',
            name='setcustprice',
            field=models.BooleanField(default=False, verbose_name='设置客户价格'),
        ),
        migrations.AlterField(
            model_name='shoppingflow',
            name='sfsubmitname',
            field=models.CharField(max_length=100, verbose_name='确认人员'),
        ),
    ]
