# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-04 11:05
from __future__ import unicode_literals

import HdWxShop.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HdWxShop', '0006_auto_20180517_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='indexshowcommodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showmany', models.IntegerField(default=5)),
                ('indexclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HdWxShop.commodityclass')),
            ],
        ),
        migrations.AddField(
            model_name='commodityinfo',
            name='logisticsimg',
            field=models.ImageField(blank=True, upload_to=HdWxShop.models.upload_commodityimg),
        ),
        migrations.AddField(
            model_name='commodityinfo',
            name='reportimg',
            field=models.ImageField(blank=True, upload_to=HdWxShop.models.upload_commodityimg),
        ),
        migrations.AlterField(
            model_name='advinfo',
            name='Advtitle',
            field=models.CharField(max_length=25),
        ),
    ]
