# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-16 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HdWxShop', '0011_auto_20180919_2251'),
    ]

    operations = [

    ]
