# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-16 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HdWxShop', '0012_auto_20181016_1521'),
    ]

    operations = [

    ]
