# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-16 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HdWxShop', '0013_auto_20181016_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingflow',
            name='flowid',
            field=models.CharField(default=-999, max_length=30),
            preserve_default=False,
        ),
    ]
