# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-16 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HdWxShop', '0014_shoppingflow_flowid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingendflow',
            name='Sefflowid',
            field=models.CharField(max_length=30, verbose_name='订单号'),
        ),
    ]
