# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-23 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HdWxShop', '0015_auto_20181016_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='indexcommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commendidx', models.IntegerField()),
                ('commenddetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HdWxShop.commditydetail')),
            ],
        ),
    ]
